version: "3"
services:
  coordinator:
    image: ahanaio/prestodb-sandbox:0.274
    tty: true
    ports:
      - "28080:8080"
    container_name: "coordinator"
    hostname: coordinator
    volumes:
      - ./config.properties:/opt/presto-server/etc/config.properties
      - ./hive.properties:/opt/presto-server/etc/catalog/hive.properties

  worker1:
    image: ahanaio/prestodb-sandbox:0.274
    container_name: "worker1"
    ports:
      - "28083:8083"
    volumes:
      - ./worker1/config.properties:/opt/presto-server/etc/config.properties
    depends_on:
      - coordinator

  worker2:
    image: ahanaio/prestodb-sandbox:0.274
    container_name: "worker2"
    ports:
      - "28084:8084"
    volumes:
      - ./worker2/config.properties:/opt/presto-server/etc/config.properties
    depends_on:
      - coordinator

  alluxio-master:
    image: sonepo/alluxio-master:1.1
    container_name: alluxio-master
    hostname: alluxio-master
    tty: true
    privileged: true
    ports:
      - 19999:19999
      - 19998:19998

  alluxio-worker1:
    image: sonepo/alluxio-worker:1.1
    container_name: alluxio-worker1
    hostname: alluxio-worker1
    tty: true
    privileged: true
    ports:
      - 29999:29999
      - 30000:30000

  alluxio-worker2:
    image: sonepo/alluxio-worker:1.1
    container_name: alluxio-worker2
    hostname: alluxio-worker2
    tty: true
    privileged: true
    ports:
      - 30001:29999
      - 30002:30000